# Generated by Django 3.0.2 on 2020-01-27 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shade',
            name='nivel_shade',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='core.Brand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='shade',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='core.Shade'),
            preserve_default=False,
        ),
    ]
